#!/bin/bash
#BSUB -R rusage[mem=10000]
#BSUB -n 4
#BSUB -J twins-jcall
#BSUB -o lsfoutputs/test-%J.out
#BSUB -e lsfoutputs/test-%J.err
# This is a script to sumbit a WDL job
# Choose a queue that you have access (eg the normal queue) and submit
# job as follows:
# ---
# bsub -q normal < WDL.lsf
# ---
# Then look in the ~/lsf/output folder for the script log
# that matches the job ID number

# Please make a copy of this script for your own modifications
module use /apps/modulefiles/lab/miket
module purge
module load bwa/0.7.10
module load sambamba/0.6.1
module load R/3.3.1
module load scala/2.11.7
module load sbt/0.13.9
module load samblaster/0.1.22
module load jdk/1.8.0
java -version
java -Dconfig.file=/PHShome/hw878/WDL_workflow/reference.conf -Xmx8000m -jar ~/WDL_workflow/cromwell-26.jar run GATK_cram.wdl GATK_cram.json